Product.create({name: "", description: "", category: "", measurement: '', color: "", price:  })
Product.create({name: "", description: "", category: "", measurement: '', color: "", price:  })
Product.create({name: "", description: "", category: "", measurement: '', color: "", price:  })
Product.create({name: "", description: "", category: "", measurement: '', color: "", price:  })
Product.create({name: "", description: "", category: "", measurement: '', color: "", price:  })