export type SessionActionTypes =
  | "RECEIVE_CURRENT_USER"
  | "LOGOUT_CURRENT_USER"
  | "RECEIVE_SESSION_ERRORS";

export enum SessionActionType {
  RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER",
  LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER",
  RECEIVE_SESSION_ERRORS = "RECEIVE_SESSION_ERRORS",
}
